version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: tic_tac_toe_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: viraj123
      MYSQL_DATABASE: tic_tac_toe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: tic_tac_toe_backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: tic_tac_toe_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
